-- Barrios de Corrientes Capital (lista depurada a partir de OpenStreetMap). Es idempotente:
-- solo agrega los que faltan. Ya se cargó en producción; queda como referencia para bases nuevas.
insert into neighborhoods (name, city, active)
select v.name, 'Corrientes', true
from (values
  ('1000 Viviendas'),
  ('17 de Agosto'),
  ('60 Viviendas'),
  ('9 de Julio'),
  ('Aldana'),
  ('Alta Gracia'),
  ('Anahí'),
  ('Apipé'),
  ('Arazaty'),
  ('Ayuda Mutua'),
  ('Bajada Vieja'),
  ('Bancario'),
  ('Bañado Norte'),
  ('Belgrano'),
  ('Berón de Astrada'),
  ('Buena Vista'),
  ('Camba Cuá'),
  ('Centro'),
  ('Cichero'),
  ('Collantes'),
  ('Concepción'),
  ('Cremonte'),
  ('Doctor Montaña'),
  ('Esperanza'),
  ('Ex Aero Club'),
  ('Florida Norte'),
  ('Galván'),
  ('General Madariaga'),
  ('Güemes'),
  ('Hipódromo'),
  ('Independencia'),
  ('Industrial'),
  ('Irupé'),
  ('Jardín'),
  ('Juan de Vera'),
  ('Juan XXIII'),
  ('La Cruz'),
  ('La Rosada'),
  ('La Toma'),
  ('Laguna Seca'),
  ('Las Malvinas'),
  ('Las Rosas'),
  ('Libertad'),
  ('Lomas del Mirador'),
  ('Luz y Fuerza'),
  ('Mercedita'),
  ('Molina Punta'),
  ('Parque Cadenas'),
  ('Pedro Ferré'),
  ('Pío X'),
  ('Pirayuí'),
  ('Plácido Martínez'),
  ('Ponce'),
  ('Popular'),
  ('Primera Junta'),
  ('Progreso'),
  ('Pujol'),
  ('Punta Tacuara'),
  ('Quinta Ferré'),
  ('Río Paraná'),
  ('Samela'),
  ('San Antonio'),
  ('San Benito'),
  ('San Gerónimo'),
  ('San Ignacio'),
  ('San Jorge'),
  ('San José'),
  ('San Marcelo'),
  ('San Marcos'),
  ('San Martín'),
  ('San Roque'),
  ('Santa Catalina'),
  ('Santa Margarita'),
  ('Santa María'),
  ('Santa Marta'),
  ('Santa Rita'),
  ('Santa Teresita'),
  ('Sapucay'),
  ('Serantes'),
  ('Sol de Mayo'),
  ('Tres de Abril'),
  ('Unión'),
  ('Universitario'),
  ('Víctor Colas'),
  ('Villa Celia'),
  ('Villa Chiquita'),
  ('Villa Ongay'),
  ('Villa Patoño'),
  ('Villa Raquel'),
  ('Virgen de la Merced'),
  ('Virgen de los Dolores'),
  ('Yapeyú')
) as v(name)
where not exists (select 1 from neighborhoods n where lower(n.name) = lower(v.name));
